version: '3.8'

services:
  app:
    image: urlshortener
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/home/node/app
